In [ ]:
# Numpy : 파이썬에서 수학과 데이터 분석을 쉽게 해주는 라이브러리
# ndArray : 숫자를 여러 차원으로 저장할 수 있는 배열

In [ ]:
import numpy as np

# 1차원 ndArray 생성(숫자 4개가 한 줄로 있는 배열)
np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4]) # numpy 배열임을 알려줌
arr2 = [1, 2, 3, 4]

# <class 'numpy.ndarray'>
# 넘파이로 이루어진 다차원 배열
print(type(arr1))

# <class 'list'>
# 파이썬 리스트 형태
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# 1차원 배열 : 숫자가 한 줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로와 세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러 장 겹친 입체 모양

# 2차원 ndArray 생성
# 1차원 배열 두개가 리스트로 묶인 형태가 2차원 배열이다.
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])

# 3차원 ndArray 생성
arr3 = np.array([[[1,2,3,4], [1,2,3,4]],
                [[1,2,3,4], [1,2,3,4]]])

print("2차원 배열 arr2")
print(arr2)

print("3차원 배열 arr3")
print(arr3)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열 arr3
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
