In [ ]:
# Numpy : 파이썬에서 수학과 데이터 분석을 쉽게 해주는 라이브러리
# ndArray : 숫자를 여러 차원으로 저장할 수 있는 배열

In [ ]:
import numpy as np

# 1차원 ndArray 생성(숫자 4개가 한 줄로 있는 배열)
np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4]) # numpy 배열임을 알려줌
arr2 = [1, 2, 3, 4]

# <class 'numpy.ndarray'>
# 넘파이로 이루어진 다차원 배열
print(type(arr1))

# <class 'list'>
# 파이썬 리스트 형태
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# 1차원 배열 : 숫자가 한 줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로와 세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러 장 겹친 입체 모양

# 2차원 ndArray 생성
# 1차원 배열 두개가 리스트로 묶인 형태가 2차원 배열이다.
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])

# 3차원 ndArray 생성
arr3 = np.array([[[1,2,3,4], [1,2,3,4]],
                [[1,2,3,4], [1,2,3,4]]])

print("2차원 배열 arr2")
print(arr2)

print("3차원 배열 arr3")
print(arr3)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열 arr3
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [5]:
# 2차원 ndArray 생성
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])

# 3차원 ndArray 생성
arr3 = np.array([[[0.1,0.2,0.3,0.4], [1,2,3,4]],
                [[1,2,3,4], [1,2,3,4]]])

print("2차원 배열 arr2")
print(arr2)

print("3차원 배열 arr3")
print(arr3)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열 arr3
[[[0.1 0.2 0.3 0.4]
  [1.  2.  3.  4. ]]

 [[1.  2.  3.  4. ]
  [1.  2.  3.  4. ]]]


In [14]:
# ndim : 배열의 차원 수
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape : 배열의 형태
print(arr1.shape) # 숫자 4개가 있는 한 줄
print(arr2.shape) # 2줄, 각 줄에 4칸
print(arr3.shape) # 2장(층), 각 장마다 2줄, 각 줄에 4칸

# size : 배열 요소의 총 개수
print(arr1.size) # 4
print(arr2.size) # 2 * 4 = 8
print(arr3.size) # 2 * 2 * 4 = 16

# dtype : 배열 요소의 데이터 타입
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

1
2
3
(4,)
(2, 4)
(2, 2, 4)
4
8
16
int64
int64
float64


In [17]:
# ndarray.T : 전치행렬
arr = np.array([[1,2,3],
               [4,5,6]])

print("원래 배열")
print(arr)

print("전치 배열")
print(arr.T)

원래 배열
[[1 2 3]
 [4 5 6]]
전치 배열
[[1 4]
 [2 5]
 [3 6]]


In [18]:
# ndArray.flatten() : 1차원으로 펼치기
arr = np.array([[1,2,3],
               [4,5,6]])

print("원래 배열")
print(arr)

print("1차원으로 펼친 배열")
print(arr.flatten())

원래 배열
[[1 2 3]
 [4 5 6]]
1차원으로 펼친 배열
[1 2 3 4 5 6]


In [ ]:
# ndArray.reshape() : 배열 모양 바꾸기
arr = np.array([1,2,3,4,5,6])
print("원래 배열")
print(arr)

arr2 = arr.reshape(2, 3) # 2행 3열로 반환
print("2행 3열 배열")
print(arr2)

원래 배열
[1 2 3 4 5 6]
2행 3열 배열
[[1 2 3]
 [4 5 6]]


In [24]:
# ndArray.sum() : 합계 구하기
# axis 옵션
# axis=0 : 열 방향 합
# axis=1 : 행 방향 합
arr = np.array([[1,2,3],
               [4,5,6]])

print("전체 합", arr.sum())

print("열 방향 합(axis=0) : ", arr.sum(axis=0))
print("행 방향 합(axis=1) : ", arr.sum(axis=1))

전체 합 21
열 방향 합(axis=0) :  [5 7 9]
행 방향 합(axis=1) :  [ 6 15]
